INSERT INTO MENUS
  VALUES(100,1,'2 Eggs and Bacon');
INSERT INTO MENUS
  VALUES(100,2,'3 Eggs, Bacon and Sausage');
INSERT INTO MENUS
  VALUES(100,3,'French Toast');
INSERT INTO MENUS
  VALUES(100,4,'Blueberry Pancakes');
INSERT INTO MENUS
  VALUES(200,5,'Miso Soup');
INSERT INTO MENUS
  VALUES(200,6,'Pad Thai');
INSERT INTO MENUS
  VALUES(200,7,'Beef Noodles');
INSERT INTO MENUS
  VALUES(200,8,'Mango Sticky Rice');
INSERT INTO MENUS
  VALUES(300,9,'Mozzarella Sticks');
INSERT INTO MENUS
  VALUES(300,10,'Garden Salad');
INSERT INTO MENUS
  VALUES(300,11,'Draft Beer');
INSERT INTO MENUS
  VALUES(300,12,'Pulled Pork Sandwich');
INSERT INTO MENUS
  VALUES(400,13,'Spaghetti and meatballs');
INSERT INTO MENUS
  VALUES(400,14,'Angel Hair seefood');
INSERT INTO MENUS
  VALUES(400,15,'Chicken Parmesan');
INSERT INTO MENUS
  VALUES(400,16,'Ceasar Salad');
INSERT INTO MENUS
  VALUES(500,17, 'Steak Burrito');
INSERT INTO MENUS
  VALUES(500,18,'Beef Taco');
INSERT INTO MENUS
  VALUES(500,19,'Mexifries');
INSERT INTO MENUS
  VALUES(500,20,'Burrito Salad');
INSERT INTO MENUS
  VALUES(600,21,'Chicken Balls');
INSERT INTO MENUS
  VALUES(600,22,'Chow Mein');
INSERT INTO MENUS
  VALUES(600,23,'Teriyaki Chicken');
INSERT INTO MENUS
  VALUES(600,24, 'Rice');