INSERT INTO RESTAURANT
VALUES('Sunset Grill',123,100,'Medium');
INSERT INTO RESTAURANT
VALUES('My-Thai',234,200,'High');
INSERT INTO RESTAURANT
VALUES('Rocklings',345,300,'Medium');
INSERT INTO RESTAURANT
VALUES('Gran Sasso Restaurant',456,400,'High');
INSERT INTO RESTAURANT
VALUES('Bar Burrito',567,500,'low');
INSERT INTO RESTAURANT
VALUES('Jumbo Dragon',678,600,'low');